image: registry.edugit.org/teckids/team-sysadmin/docker-images/python-pimped:latest

stages:
      - test
      - build

include:
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/general.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/test.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/build_dist.yml
